### ISSUE TITLE
Security Misconfiguration: Use of HTTP Without TLS/SSL

### ISSUE THREAD

**Issue by akondasif** [Mimetis/Jhispter-Kubernetes#1]

**Comment by akondasif** [comment]
We have noticed an instance of not using rolling updates. Rolling updates helps to automatically apply continuous updates. Without continuous updates, a Kubernetes cluster will be susceptible to a denial of service attack, according to researchers: https://arxiv.org/pdf/2006.15275.pdf .


Location: https://github.com/Mimetis/Jhispter-Kubernetes/blob/52c4ae319849c8e10372ab20612664d1f5aaf8bb/kubernetes/catalog/catalog-deployment.yml#L7

**Comment by akondasif** [comment]
We have noticed an instance of HTTP without TLS/SSL in one of your Kubernetes manifests. The recommended practice is use of secure HTTP for each team's development and production environment. Enabling TLS ensures secure communication between cluster components.. For examples of Kubernetes security anti-patterns we are following our peer-reviewed publication on Kubernetes security best practices (https://arxiv.org/pdf/2006.15275.pdf).

Location:

https://github.com/Mimetis/Jhispter-Kubernetes/blob/52c4ae319849c8e10372ab20612664d1f5aaf8bb/kubernetes/uaa/uaa-deployment.yml#L21

Please use SSL/TLS to fix this misconfiguration. We would like to hear if you agree to fix this misconfiguration or have fixed the misconfiguration.

**Comment by Mimetis** [comment]
I know you are a bot, but just in case, this repo is JUST A SAMPLE :)

**Comment by akondasif** [comment]
Thanks. Closing this issue.
